# Generated by Django 3.2.4 on 2021-11-13 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('emailid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 10, 8, 56, 245760)),
        ),
        migrations.AlterField(
            model_name='person',
            name='block_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 10, 8, 56, 245760)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 10, 8, 56, 245760)),
        ),
    ]
