# Generated by Django 3.2.4 on 2021-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0002_auto_20211113_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
