# Generated by Django 3.2.4 on 2021-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0004_auto_20211114_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
    ]
