# Generated by Django 3.2.4 on 2021-11-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0005_room_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
